-- Auto-generated from schema-map-postgres.yaml (map@sha1:6D9B52237D942B2B3855FD0F5500331B935A7C62)
-- engine: postgres
-- table:  key_wrapper_layers

CREATE TABLE IF NOT EXISTS key_wrapper_layers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key_wrapper_id BIGINT NOT NULL,
  layer_no SMALLINT NOT NULL,                -- 1..N layer order
  kms_key_id BIGINT NULL,                    -- optional: reference to a KMS key
  kem_algo_id BIGINT NOT NULL,               -- odkaz na crypto_algorithms (class='kem')
  kem_ciphertext BYTEA NOT NULL,             -- encapsulated key (ready for longer PQC ciphertext)
  encap_pubkey BYTEA NULL,                   -- for hybrid/external KEM as needed
  aad JSONB NULL,                            -- AAD used during wrapping
  meta JSONB NULL,                           -- e.g. { "hybrid_with": "x25519" }
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_kwl UNIQUE (key_wrapper_id, layer_no)
);
